import { VerticalBox, Button, GroupBox, AboutSlint, HorizontalBox, ListView, Slider, TabWidget, ScrollView, GridBox } from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 600px;
    height: 480px;
    title: "书签管理器";

    HorizontalBox {
        spacing: 20px;
        GroupBox {
            width: 30%;
            VerticalLayout {
                GridBox {
                    Rectangle {}
                    Button {
                        primary: true;
                        text: "添加";
                    }
                    Button {

                        text: "删除";
                    }
                }
                // 水平分割线
                Rectangle {
                    width: 5%; // 细线宽度
                    height: 1px; // 填充父元素高度
                    background: gray; // 分割线颜色
                }
                
                VerticalBox {
                    ScrollView {
                        height: 95%;
                        for data in [
                            { text: "书签1", color: #fff},
                            { text: "书签2", color: #fff},
                            { text: "书签3", color: #fff},
                        ]:Text {
                            x: 0;
                            text: data.text;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                        }
                    }
                    Rectangle {
                        height: 10px;
                        width: 100%;
                        Text {
                            text: "h";
                        }
                    }
                }
            }
        }

        GroupBox {
        }
    }
}